sudo: travis
language: python
python:
  - "2.7"
  - "3.3"
  - "3.4"
  - "3.5"
  - "3.6"
  - "pypy"
  - "pypy3"

install:
  - pip install -U setuptools pip sphinx tox
  - pip install -r requirements/dev.pip

script:
  - ./bin/test_standalone.sh
  - tox
  - ./bin/check_readme.sh

branches:
  except:
    - standalone
